In [2]:
import numpy as np;

In [3]:
y = np.linspace(0,20,11)

In [4]:
y

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [5]:
y[[1,1,2,8,4,9,3]]

array([ 2.,  2.,  4., 16.,  8., 18.,  6.])

In [13]:
y_bool = y > 7

In [14]:
y_bool

array([False, False, False, False, False, False, False, False,  True,
        True,  True])

In [8]:
y[y>7] = y[y>7]/2
y

array([ 0.,  2.,  4.,  6.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
y2 = y

In [11]:
y2[-1] = 30
y2

array([ 0.,  2.,  4.,  6.,  4.,  5.,  6.,  7.,  8.,  9., 30.])

In [12]:
y

array([ 0.,  2.,  4.,  6.,  4.,  5.,  6.,  7.,  8.,  9., 30.])

In [17]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3])
a+b
# You can add arrays with different sizes. Hence the error.

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [18]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
a+b

array([11, 22, 33, 44])

Array broadcasting

In [20]:
x = np.arange(-6,6).reshape(4,3)
x

array([[-6, -5, -4],
       [-3, -2, -1],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [25]:
a =np.array([1,2,3])
b =np.array([100])
c =np.array([1,2,3,4])
d =np.array([[10],[20],[30],[40]])
e =np.array([[3,2,1]])
f =np.array([[10000]])
g =np.array([[100],[200],[300]])

Equal or 1

In [38]:
d2 = np.array([[10, 1],[20, 2],[30, 3],[40, 4]])
d2

array([[10,  1],
       [20,  2],
       [30,  3],
       [40,  4]])

In [40]:
d2.shape, x.shape

((4, 2), (4, 3))

In [35]:
d
d.shape

(4, 1)

In [36]:
d

array([[10],
       [20],
       [30],
       [40]])

In [26]:
x + a

array([[-5, -3, -1],
       [-2,  0,  2],
       [ 1,  3,  5],
       [ 4,  6,  8]])

In [27]:
x + b

array([[ 94,  95,  96],
       [ 97,  98,  99],
       [100, 101, 102],
       [103, 104, 105]])

In [29]:
d.shape, x.shape

((4, 1), (4, 3))

In [30]:
d + x

array([[ 4,  5,  6],
       [17, 18, 19],
       [30, 31, 32],
       [43, 44, 45]])

In [31]:
e.shape, x.shape

((1, 3), (4, 3))

In [32]:
e + x

array([[-3, -3, -3],
       [ 0,  0,  0],
       [ 3,  3,  3],
       [ 6,  6,  6]])